export default {
  CREATE_TODO: "CREATE_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_TODO_STATUS: "CHANGE_TODO_STATUS",
  COMPLETE_ALL: "COMPLETE_ALL",
  CHANGE_CURRENT_SORT: "CHANGE_CURRENT_SORT",
};
