export default {
  CREATE_TODO: "CREATE_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_TODO_STATUS: "CHANGE_TODO_STATUS",
  COMPLETE_ALL: "COMPLETE_ALL",
  CHANGE_CURRENT_FILTER: "CHANGE_CURRENT_FILTER",
  CLEAR_COMPLETED_TODOS: "CLEAR_COMPLETED_TODOS",
};
